### ISSUE TITLE
内容过长，省略显示

### ISSUE THREAD

**Issue by oneIdler** [atomicoke/chatWeb#5]
## 现在
![image](https://user-images.githubusercontent.com/75054953/165219237-16a8eff5-a8f0-47b4-b291-4472ad92e009.png)
## 预期
![image](https://user-images.githubusercontent.com/75054953/165219149-8e4ef430-5353-47b7-a2f4-58465d18527e.png)

**Comment by fzdwx** [comment]
撑起来了。
![image](https://user-images.githubusercontent.com/65269574/167298354-25c05940-98cb-4899-b041-20eaed9bf237.png)
